# Pandas

데이터 프레임을 생성해서 관리할 수 있는 패키지

In [1]:
import pandas as pd
import numpy as np

### 시리즈

데이터프레임을 구성하는 특성하나. 1차원 배열과 비슷 

In [2]:
data1 = [9904312, 3448737, 2890451, 2466052]
s1 = pd.Series(data1)
s1

0    9904312
1    3448737
2    2890451
3    2466052
dtype: int64

In [3]:
data1 = [9904312, 3448737, 2890451, 2466052]
index1 = ['서울', '부산', '인천', '대구']
s1 = pd.Series(data1, index=index1)
s1

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [4]:
# 시리즈에서 값만 추출한다.
print(s1.values)

[9904312 3448737 2890451 2466052]


In [5]:
# ################################################시리즈에서 인덱스만 추출한다.
print(s1.index)

Index(['서울', '부산', '인천', '대구'], dtype='object')


In [6]:
# 시리즈의 이름을 세팅한다.
s1.name = '인구'
s1

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

# 시리즈 연산

numpy랑 똑같음

In [7]:
print(s1)
print(s1 + 1000000)
print(s1 + 1000000)
print(s1 * 10)
print(s1 // 10)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64
서울    10904312
부산     4448737
인천     3890451
대구     3466052
Name: 인구, dtype: int64
서울    10904312
부산     4448737
인천     3890451
대구     3466052
Name: 인구, dtype: int64
서울    99043120
부산    34487370
인천    28904510
대구    24660520
Name: 인구, dtype: int64
서울    990431
부산    344873
인천    289045
대구    246605
Name: 인구, dtype: int64


### 시리즈 인덱싱

In [8]:
s1

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [9]:
print(s1[1])
print(s1['부산'])

3448737
3448737


In [10]:
# 다수의 값을 선택해서 가져온다.
print(s1[[0, 1, 2]])
print(s1[['서울', '부산', '인천', '대구']])

서울    9904312
부산    3448737
인천    2890451
Name: 인구, dtype: int64
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64


In [11]:
print(s1[[2, 0, 1]])
print(s1[['인천', '서울', '부산', '대구']])

인천    2890451
서울    9904312
부산    3448737
Name: 인구, dtype: int64
인천    2890451
서울    9904312
부산    3448737
대구    2466052
Name: 인구, dtype: int64


In [12]:
# true나 false가 들어 있는 리스트, 배열, 시리즈를 넣어주면 True에 해당하는 값들만 모아 새로운 시리즈로 생성한다.
t1 = [True, False, True, False]
print(s1[t1])

서울    9904312
인천    2890451
Name: 인구, dtype: int64


In [13]:
# 시리즈를 가지고 True나 False의 결과를 생성하는 수식을 넣어주면 원하는 조건에 맞느 ㄴ데이터만 가져올 수 있도록 구현할 수 있다.
print(s1[s1 > 3000000])

서울    9904312
부산    3448737
Name: 인구, dtype: int64


In [14]:
# 범위 지정

# 1 ~ 3-1
print(s1[1:3])

#서울 ~ 인천
print(s1['서울':'인천'])

부산    3448737
인천    2890451
Name: 인구, dtype: int64
서울    9904312
부산    3448737
인천    2890451
Name: 인구, dtype: int64


In [15]:
# 만약 시리즈의 인덱스가 문자열로 되어 있다면 . 을 통해서 가져올 수 있다.
print(s1['서울'])
print(s1.서울)

9904312
9904312


In [16]:
# 시리즈의 인덱스가 숫자로 되어있다면...
data2 = [9904312, 3448737, 2890451, 2466052]
s2 = pd.Series(data1)
s2

0    9904312
1    3448737
2    2890451
3    2466052
dtype: int64

In [18]:
for value in s2 :
    print(value)

9904312
3448737
2890451
2466052


In [19]:
# 시리즈의 인덱스가 문자열로 되어 있다면
data3 = [9904312, 3448737, 2890451, 2466052]
index3 = ['서울', '부산', '인천', '대구']
s3 = pd.Series(data1, index=index1)
s3

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [20]:
for value in s3 :
    print(value)

9904312
3448737
2890451
2466052


In [21]:
for key, value in s3.items() :
    print(key, value)

서울 9904312
부산 3448737
인천 2890451
대구 2466052


In [24]:
# 시리즈 생성
s10 = pd.Series([100, 200, 300, 400, 500], index=['v1', 'v2', 'v3', 'v4', 'v5'])
print(s10)

v1    100
v2    200
v3    300
v4    400
v5    500
dtype: int64


In [26]:
s20 = pd.Series({'v1':100, 'v2':200, 'v3':300})
s20

v1    100
v2    200
v3    300
dtype: int64

In [29]:
# index를 따로 세팅해주면 세팅한 순서대로 시리즈가 만들어지며 존재하지 않는 index의 경의 결측치로 채워진다.
s30 = pd.Series({'v1':100, 'v2':200, 'v3':300}, index=['v2', 'v3', 'v1'])
s30

v2    200
v3    300
v1    100
dtype: int64

### 시리즈 연산

In [30]:
s100 = pd.Series([10, 20, 30], index=['a1', 'a2', 'a3'])
s200 = pd.Series([40, 50, 60], index=['a2', 'a3', 'a4'])

In [31]:
print(s100)
print(s200)

a1    10
a2    20
a3    30
dtype: int64
a2    40
a3    50
a4    60
dtype: int64


In [32]:
r1 = s100 + s200
r1

a1     NaN
a2    60.0
a3    80.0
a4     NaN
dtype: float64

In [35]:
r2 = s100.values + s200.values
print(s100.values)
print(s200.values)
print(r2)

[10 20 30]
[40 50 60]
[50 70 90]


In [37]:
s300 = pd.Series([10, 20, 30], index=['a1', 'a2', 'a3'])
s400 = pd.Series([40, 50], index=['a1', 'a2'])
print(s300 +s400)

a1    50.0
a2    70.0
a3     NaN
dtype: float64


In [40]:
(s300 + s400).notnull()

a1     True
a2     True
a3    False
dtype: bool

In [41]:
# 계산 후 결측치 부분을 제외하고 가져온다.
r100 = s300 + s400
print(r100[r100.notnull()])

# 결측치 부분을 원하는 값으로 채워준다
print(r100.fillna(0))

a1    50.0
a2    70.0
dtype: float64
a1    50.0
a2    70.0
a3     0.0
dtype: float64


### 갱신추가 삭제

In [42]:
s500 = pd.Series([10, 20, 30], index=['v1', 'v2', 'v3'])
s500

v1    10
v2    20
v3    30
dtype: int64

In [43]:
s500['v1'] = 100
s500

v1    100
v2     20
v3     30
dtype: int64

In [44]:
s500['v4'] = 40
s500

v1    100
v2     20
v3     30
v4     40
dtype: int64

In [45]:
del s500['v4']
s500

v1    100
v2     20
v3     30
dtype: int64